name: Test Hanzo Net

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov
        pip install -e .
    
    - name: Run tests
      run: |
        python -m pytest test/ -v --cov=net --cov-report=term-missing
    
    - name: Test import
      run: |
        python -c "from net.main import run; print('Import successful')"

  integration:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install hanzo/net
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test node startup
      run: |
        timeout 10 python -c "from net.main import run; print('Node test')" || true
    
    - name: Check dependencies
      run: |
        python -c "import scapy, aiohttp, grpcio, pydantic, transformers; print('All deps OK')"